# Generated by Django 6.1 on 2026-08-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الماركة")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/",
                        verbose_name="شعار الماركة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ماركة",
                "verbose_name_plural": "الماركات",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="الرابط اللطيف (Slug)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف القسم"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="صورة القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المنتج")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الأساسي"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر بعد الخصم",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="وصف المنتج وطريقة الاستخدام"),
                ),
                (
                    "suitable_skin_type",
                    models.CharField(
                        choices=[
                            ("all", "جميع أنواع البشرة"),
                            ("dry", "البشرة الجافة"),
                            ("oily", "البشرة الدهنية"),
                            ("combination", "البشرة المختلطة"),
                            ("normal", "البشرة العادية"),
                            ("sensitive", "البشرة الحساسة"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="مناسب لنوع البشرة",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متوفر في المخزون"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="منتج مميز (يظهر بالرئيسية)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.brand",
                        verbose_name="الماركة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
            },
        ),
        migrations.CreateModel(
            name="ProductShade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shade_name",
                    models.CharField(max_length=100, verbose_name="اسم الدرجة / اللون"),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="كود اللون Hex (مثال: #FF5733)",
                    ),
                ),
                (
                    "shade_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/shades/",
                        verbose_name="صورة الدرجة",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية المتوفرة"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shades",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "درجة / لون",
                "verbose_name_plural": "درجات الألوان",
            },
        ),
    ]
