# Generated by Django 6.1 on 2026-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="صورة المنتج (من الجهاز)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="رابط الصورة (من الإنترنت)",
            ),
        ),
    ]
